### PR TITLE
Tx summary new style

### PR DESCRIPTION
**Pull request by hard75**

### CODE REVIEW

**Review by alexjavabraz — DISMISSED** [review]
LGTM

**Comment by ronaldsg20** [comment]
Can you please remove the last merge commit? @alexjavabraz

**Comment by alexjavabraz** [comment]
> Can you please remove the last merge commit? @alexjavabraz

reverted, we will need to use rebase instead of merge commit.

**Review by alexjavabraz — APPROVED** [review]
LGTM

**Review by ronaldsg20 — APPROVED** [review]

**Comment by hard75** [comment]
Task have new branch

**Pull request closed without merging**
