### PR TITLE
Fixing Confirmation page observations

### PR DESCRIPTION
**Pull request by ronaldsg20**
- [x] Review all transaction information
		- [x] Maintain all boxes with the same width
		- [x] Use 2 lines to display the addresses
		- [x] Include 0x at IN THE OP_RETURN for Ledger only
		- [x] For Trezor hdwallet display only 3 columns
		- [x] Remove unused information for native
		- [x] Remove unused information for flyover
		- [x] Include the copy button in all addresses
		- [x] Include the button to see address in the explorer

### CODE REVIEW

**Comment by ronaldsg20** [comment]
image

**Review by alexjavabraz — APPROVED** [review]
LGTM

**Comment by annipi** [comment]
For flyover Pegin confirm bar is bigger than steps columns
Screenshot 2024-08-23 at 12 59 35 PM

**Review by leoiovlabs — APPROVED** [review]
LGTM

**Pull request merged**
